version: "3.9"

services:
  db:
    image: postgres:14
    container_name: postgres-cont
    environment:
      - POSTGRES_USER=natali
      - POSTGRES_PASSWORD=8409
      - POSTGRES_DB=firstdb
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
