version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=natali
      - DB_PASSWORD=8409
      - DB_NAME=firstdb
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=natali
      - POSTGRES_PASSWORD=8409
      - POSTGRES_DB=firstdb
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
